### PR TITLE
Fix percentages

### LINKED ISSUE #1: Doesn't account for percentages
```js
gbaRegex().exec("rgba(50%, 50%, 50%, .5)"); // null
```

Percentages are valid for `rgba` properties

### PR DESCRIPTION
**Pull request by tswaters**
Fixes #1 

Also need to update CI because mocha doesn't run on oldnode anymore 😄

### CODE REVIEW

**Comment by tunnckoCore** [comment]
Thanks!

**Comment by tunnckoCore** [comment]
@johno would you mind adding me on NPM?

**Comment by johno** [comment]
Sure thing, what's your npm handle?

**Comment by tunnckoCore** [comment]
same as here, `tunnckocore`

**Comment by johno** [comment]
Done 👍

**Pull request merged**
